version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mynetwork

  # Spring Boot application service
  springboot-app:
    build: .
    container_name: springboot-container
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mynetwork

volumes:
  mongodb-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
